
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    public enum BarrageTriggerType
    {
        /// <summary>
        /// 随时
        /// </summary>
        EveryTime = 0,

        /// <summary>
        /// 吃饭
        /// </summary>
        EatFood = 1,

        /// <summary>
        /// 吃屎
        /// </summary>
        EatShit = 2,

        /// <summary>
        /// 巴掌
        /// </summary>
        Hand = 3,

        /// <summary>
        /// 屎降临
        /// </summary>
        ShitDown = 4,

    }
