
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public partial class ConstConfigCategory
{

     private readonly ConstConfig _data;

     public ConstConfig Data => _data;

    public ConstConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::ConstConfig.DeserializeConstConfig(_buf);
    }


    /// <summary>
    /// 食物检测距离
    /// </summary>
     public float FoodCheckDistance => _data.FoodCheckDistance;
    /// <summary>
    /// 偷瞄检测距离
    /// </summary>
     public float PeekCheckDistance => _data.PeekCheckDistance;
    /// <summary>
    /// 偷瞄到偷吃等到时间(ms)
    /// </summary>
     public long EatSecretlyInterval => _data.EatSecretlyInterval;
    /// <summary>
    /// 食物进入下一个阶段时间间隔(ms)
    /// </summary>
     public long FoodChangeStateInterval => _data.FoodChangeStateInterval;
    /// <summary>
    /// 击打效果持续时间(ms)
    /// </summary>
     public long HitDuration => _data.HitDuration;
    /// <summary>
    /// 转向食物时间(s)
    /// </summary>
     public float TurnRotateToFoodDuration => _data.TurnRotateToFoodDuration;
    /// <summary>
    /// 新生成食物时间(ms)
    /// </summary>
     public long NewFruitTime => _data.NewFruitTime;
    /// <summary>
    /// 新屎生成时间(ms)
    /// </summary>
     public long NewShitTime => _data.NewShitTime;
    /// <summary>
    /// 屎向下移动时间(s)
    /// </summary>
     public float ShitMoveYTime => _data.ShitMoveYTime;
    /// <summary>
    /// 屎被吃完的时间(ms)
    /// </summary>
     public long ShitBeEatenTime => _data.ShitBeEatenTime;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }

    partial void InitEnd();
}
