
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public sealed partial class ConstConfig : Luban.BeanBase
{
    public ConstConfig(ByteBuf _buf) 
    {
        FoodCheckDistance = _buf.ReadFloat();
        PeekCheckDistance = _buf.ReadFloat();
        EatSecretlyInterval = _buf.ReadLong();
        FoodChangeStateInterval = _buf.ReadLong();
        HitDuration = _buf.ReadLong();
        TurnRotateToFoodDuration = _buf.ReadFloat();
        NewFruitTime = _buf.ReadLong();
        NewShitTime = _buf.ReadLong();
        ShitMoveYTime = _buf.ReadFloat();
        ShitBeEatenTime = _buf.ReadLong();
        SCGreenDuration = _buf.ReadInt();
        SCOrangeDuration = _buf.ReadInt();
        SCSpawnInterval = _buf.ReadInt();
        SCMaxTaskCount = _buf.ReadInt();
        SCGreenProbability = _buf.ReadFloat();
    }

    public static ConstConfig DeserializeConstConfig(ByteBuf _buf)
    {
        return new ConstConfig(_buf);
    }

    /// <summary>
    /// 食物检测距离
    /// </summary>
    public readonly float FoodCheckDistance;
    /// <summary>
    /// 偷瞄检测距离
    /// </summary>
    public readonly float PeekCheckDistance;
    /// <summary>
    /// 偷瞄到偷吃等到时间(ms)
    /// </summary>
    public readonly long EatSecretlyInterval;
    /// <summary>
    /// 食物进入下一个阶段时间间隔(ms)
    /// </summary>
    public readonly long FoodChangeStateInterval;
    /// <summary>
    /// 击打效果持续时间(ms)
    /// </summary>
    public readonly long HitDuration;
    /// <summary>
    /// 转向食物时间(s)
    /// </summary>
    public readonly float TurnRotateToFoodDuration;
    /// <summary>
    /// 新生成食物时间(ms)
    /// </summary>
    public readonly long NewFruitTime;
    /// <summary>
    /// 新屎生成时间(ms)
    /// </summary>
    public readonly long NewShitTime;
    /// <summary>
    /// 屎向下移动时间(s)
    /// </summary>
    public readonly float ShitMoveYTime;
    /// <summary>
    /// 屎被吃完的时间(ms)
    /// </summary>
    public readonly long ShitBeEatenTime;
    /// <summary>
    /// 绿色任务秒数(s)
    /// </summary>
    public readonly int SCGreenDuration;
    /// <summary>
    /// 橙色任务秒数(s)
    /// </summary>
    public readonly int SCOrangeDuration;
    /// <summary>
    /// 生成间隔秒数(s)
    /// </summary>
    public readonly int SCSpawnInterval;
    /// <summary>
    /// 最大任务数
    /// </summary>
    public readonly int SCMaxTaskCount;
    /// <summary>
    /// 绿色概率
    /// </summary>
    public readonly float SCGreenProbability;
   
    public const int __ID__ = -1271334811;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        InitEnd();
    }

    public override string ToString()
    {
        return "{ "
        + "FoodCheckDistance:" + FoodCheckDistance + ","
        + "PeekCheckDistance:" + PeekCheckDistance + ","
        + "EatSecretlyInterval:" + EatSecretlyInterval + ","
        + "FoodChangeStateInterval:" + FoodChangeStateInterval + ","
        + "HitDuration:" + HitDuration + ","
        + "TurnRotateToFoodDuration:" + TurnRotateToFoodDuration + ","
        + "NewFruitTime:" + NewFruitTime + ","
        + "NewShitTime:" + NewShitTime + ","
        + "ShitMoveYTime:" + ShitMoveYTime + ","
        + "ShitBeEatenTime:" + ShitBeEatenTime + ","
        + "SCGreenDuration:" + SCGreenDuration + ","
        + "SCOrangeDuration:" + SCOrangeDuration + ","
        + "SCSpawnInterval:" + SCSpawnInterval + ","
        + "SCMaxTaskCount:" + SCMaxTaskCount + ","
        + "SCGreenProbability:" + SCGreenProbability + ","
        + "}";
    }

    partial void InitEnd();
}
