
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public sealed partial class DanmakuPoolConfig : Luban.BeanBase
{
    public DanmakuPoolConfig(ByteBuf _buf) 
    {
        StateType = _buf.ReadInt();
        MinInterval = _buf.ReadFloat();
        MaxInterval = _buf.ReadFloat();
    }

    public static DanmakuPoolConfig DeserializeDanmakuPoolConfig(ByteBuf _buf)
    {
        return new DanmakuPoolConfig(_buf);
    }

    /// <summary>
    /// 状态类型(0=Anytime,1=Eating,2=Hit,3=EatShit,4=ShitSpawn)
    /// </summary>
    public readonly int StateType;
    /// <summary>
    /// 最小生成间隔(s)
    /// </summary>
    public readonly float MinInterval;
    /// <summary>
    /// 最大生成间隔(s)
    /// </summary>
    public readonly float MaxInterval;
   
    public const int __ID__ = -980602675;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        InitEnd();
    }

    public override string ToString()
    {
        return "{ "
        + "StateType:" + StateType + ","
        + "MinInterval:" + MinInterval + ","
        + "MaxInterval:" + MaxInterval + ","
        + "}";
    }

    partial void InitEnd();
}
