
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public partial class DanmakuContentConfigCategory
{
    private readonly System.Collections.Generic.List<DanmakuContentConfig> _dataList;


    public DanmakuContentConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<DanmakuContentConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DanmakuContentConfig _v;
            _v = global::DanmakuContentConfig.DeserializeDanmakuContentConfig(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<DanmakuContentConfig> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    partial void InitEnd();
}
