
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public sealed partial class DanmakuContentConfig : Luban.BeanBase
{
    public DanmakuContentConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        StateType = _buf.ReadInt();
        Content = _buf.ReadString();
        Weight = _buf.ReadInt();
    }

    public static DanmakuContentConfig DeserializeDanmakuContentConfig(ByteBuf _buf)
    {
        return new DanmakuContentConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 状态类型
    /// </summary>
    public readonly int StateType;
    /// <summary>
    /// 	弹幕内容
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = -2055462804;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        InitEnd();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "StateType:" + StateType + ","
        + "Content:" + Content + ","
        + "Weight:" + Weight + ","
        + "}";
    }

    partial void InitEnd();
}
