
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    public enum FoodType
    {
        None = 0,

        /// <summary>
        /// 黄瓜
        /// </summary>
        Cucumber = 1,

        /// <summary>
        /// 南瓜
        /// </summary>
        Pumpkin = 2,

        /// <summary>
        /// 鸡腿
        /// </summary>
        ChickenLeg = 3,

        /// <summary>
        /// 苹果
        /// </summary>
        Apple = 4,

        /// <summary>
        /// 西兰花
        /// </summary>
        Broccoli = 5,

        /// <summary>
        /// 饼干
        /// </summary>
        Biscuit = 6,

        /// <summary>
        /// 蓝莓A
        /// </summary>
        Blueberry_A = 7,

        /// <summary>
        /// 蓝莓B
        /// </summary>
        Blueberry_B = 8,

        /// <summary>
        /// 蓝莓C
        /// </summary>
        Blueberry_C = 9,

        /// <summary>
        /// 蓝莓D
        /// </summary>
        Blueberry_D = 10,

        /// <summary>
        /// 胡萝卜
        /// </summary>
        Carrot = 11,

        /// <summary>
        /// 蛋
        /// </summary>
        Egg = 12,

        /// <summary>
        /// 三文鱼
        /// </summary>
        Salmon = 13,

        /// <summary>
        /// 虾
        /// </summary>
        Shrimp = 14,

        /// <summary>
        /// 屎
        /// </summary>
        Shit = 15,

    }
