
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public partial class FoodConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<FoodType, FoodConfig> _dataMap;
    private readonly System.Collections.Generic.List<FoodConfig> _dataList;
    
    public FoodConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<FoodType, FoodConfig>(n);
        _dataList = new System.Collections.Generic.List<FoodConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            FoodConfig _v;
            _v = global::FoodConfig.DeserializeFoodConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FoodType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<FoodType, FoodConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<FoodConfig> DataList => _dataList;

    public FoodConfig GetOrDefault(FoodType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public FoodConfig Get(FoodType key) => _dataMap[key];
    public FoodConfig this[FoodType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        InitEnd();
    }


    partial void InitEnd();
}
