
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public sealed partial class FoodConfig : Luban.BeanBase
{
    public FoodConfig(ByteBuf _buf) 
    {
        FoodType = (FoodType)_buf.ReadInt();
        FoodStateCount = _buf.ReadInt();
        HasReamin = _buf.ReadBool();
        UIResName = _buf.ReadString();
        IconResName = _buf.ReadString();
    }

    public static FoodConfig DeserializeFoodConfig(ByteBuf _buf)
    {
        return new FoodConfig(_buf);
    }

    /// <summary>
    /// 食物类型
    /// </summary>
    public readonly FoodType FoodType;
    /// <summary>
    /// 食物状态数量
    /// </summary>
    public readonly int FoodStateCount;
    /// <summary>
    /// 吃完是否有剩余
    /// </summary>
    public readonly bool HasReamin;
    public readonly string UIResName;
    public readonly string IconResName;
   
    public const int __ID__ = 1123490144;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        InitEnd();
    }

    public override string ToString()
    {
        return "{ "
        + "FoodType:" + FoodType + ","
        + "FoodStateCount:" + FoodStateCount + ","
        + "HasReamin:" + HasReamin + ","
        + "UIResName:" + UIResName + ","
        + "IconResName:" + IconResName + ","
        + "}";
    }

    partial void InitEnd();
}
