
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public partial class InputKeyMapCategory
{
    private readonly System.Collections.Generic.Dictionary<int, InputKeyMapConfig> _dataMap;
    private readonly System.Collections.Generic.List<InputKeyMapConfig> _dataList;
    
    public InputKeyMapCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, InputKeyMapConfig>(n);
        _dataList = new System.Collections.Generic.List<InputKeyMapConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            InputKeyMapConfig _v;
            _v = global::InputKeyMapConfig.DeserializeInputKeyMapConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, InputKeyMapConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<InputKeyMapConfig> DataList => _dataList;

    public InputKeyMapConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public InputKeyMapConfig Get(int key) => _dataMap[key];
    public InputKeyMapConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        InitEnd();
    }


    partial void InitEnd();
}
