
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public sealed partial class InputKeyMapConfig : Luban.BeanBase
{
    public InputKeyMapConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Change = _buf.ReadString();
        MoveW = _buf.ReadString();
        MoveA = _buf.ReadString();
        MoveS = _buf.ReadString();
        MoveD = _buf.ReadString();
        RotateL = _buf.ReadString();
        RotateR = _buf.ReadString();
        Hold = _buf.ReadString();
        Hit = _buf.ReadString();
    }

    public static InputKeyMapConfig DeserializeInputKeyMapConfig(ByteBuf _buf)
    {
        return new InputKeyMapConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 切换手势
    /// </summary>
    public readonly string Change;
    /// <summary>
    /// 向前移动
    /// </summary>
    public readonly string MoveW;
    /// <summary>
    /// 向左移动
    /// </summary>
    public readonly string MoveA;
    /// <summary>
    /// 向后移动
    /// </summary>
    public readonly string MoveS;
    /// <summary>
    /// 向右移动
    /// </summary>
    public readonly string MoveD;
    /// <summary>
    /// 左旋转
    /// </summary>
    public readonly string RotateL;
    /// <summary>
    /// 右旋转
    /// </summary>
    public readonly string RotateR;
    /// <summary>
    /// 握住
    /// </summary>
    public readonly string Hold;
    /// <summary>
    /// 击打
    /// </summary>
    public readonly string Hit;
   
    public const int __ID__ = -1826985751;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        InitEnd();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Change:" + Change + ","
        + "MoveW:" + MoveW + ","
        + "MoveA:" + MoveA + ","
        + "MoveS:" + MoveS + ","
        + "MoveD:" + MoveD + ","
        + "RotateL:" + RotateL + ","
        + "RotateR:" + RotateR + ","
        + "Hold:" + Hold + ","
        + "Hit:" + Hit + ","
        + "}";
    }

    partial void InitEnd();
}
