
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public partial class ScoreConfigCategory
{

     private readonly ScoreConfig _data;

     public ScoreConfig Data => _data;

    public ScoreConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::ScoreConfig.DeserializeScoreConfig(_buf);
    }


    /// <summary>
    /// 1口食物分数
    /// </summary>
     public int FoodScore1Bite => _data.FoodScore1Bite;
    /// <summary>
    /// 2口食物分数
    /// </summary>
     public int FoodScore2Bite => _data.FoodScore2Bite;
    /// <summary>
    /// 3口食物分数
    /// </summary>
     public int FoodScore3Bite => _data.FoodScore3Bite;
    /// <summary>
    /// 偷吃扣分
    /// </summary>
     public int SecretEatPenalty => _data.SecretEatPenalty;
    /// <summary>
    /// 错误打狗扣分
    /// </summary>
     public int WrongHitPenalty => _data.WrongHitPenalty;
    /// <summary>
    /// 吃屎扣分
    /// </summary>
     public int EatShitPenalty => _data.EatShitPenalty;
    /// <summary>
    /// 绿色任务倍率
    /// </summary>
     public float TaskMultiplierGreen => _data.TaskMultiplierGreen;
    /// <summary>
    /// 橙色任务倍率
    /// </summary>
     public float TaskMultiplierOrange => _data.TaskMultiplierOrange;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }

    partial void InitEnd();
}
