
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public sealed partial class ScoreConfig : Luban.BeanBase
{
    public ScoreConfig(ByteBuf _buf) 
    {
        FoodScore1Bite = _buf.ReadInt();
        FoodScore2Bite = _buf.ReadInt();
        FoodScore3Bite = _buf.ReadInt();
        SecretEatPenalty = _buf.ReadInt();
        WrongHitPenalty = _buf.ReadInt();
        EatShitPenalty = _buf.ReadInt();
        TaskMultiplierGreen = _buf.ReadFloat();
        TaskMultiplierOrange = _buf.ReadFloat();
    }

    public static ScoreConfig DeserializeScoreConfig(ByteBuf _buf)
    {
        return new ScoreConfig(_buf);
    }

    /// <summary>
    /// 1口食物分数
    /// </summary>
    public readonly int FoodScore1Bite;
    /// <summary>
    /// 2口食物分数
    /// </summary>
    public readonly int FoodScore2Bite;
    /// <summary>
    /// 3口食物分数
    /// </summary>
    public readonly int FoodScore3Bite;
    /// <summary>
    /// 偷吃扣分
    /// </summary>
    public readonly int SecretEatPenalty;
    /// <summary>
    /// 错误打狗扣分
    /// </summary>
    public readonly int WrongHitPenalty;
    /// <summary>
    /// 吃屎扣分
    /// </summary>
    public readonly int EatShitPenalty;
    /// <summary>
    /// 绿色任务倍率
    /// </summary>
    public readonly float TaskMultiplierGreen;
    /// <summary>
    /// 橙色任务倍率
    /// </summary>
    public readonly float TaskMultiplierOrange;
   
    public const int __ID__ = -1577541548;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        InitEnd();
    }

    public override string ToString()
    {
        return "{ "
        + "FoodScore1Bite:" + FoodScore1Bite + ","
        + "FoodScore2Bite:" + FoodScore2Bite + ","
        + "FoodScore3Bite:" + FoodScore3Bite + ","
        + "SecretEatPenalty:" + SecretEatPenalty + ","
        + "WrongHitPenalty:" + WrongHitPenalty + ","
        + "EatShitPenalty:" + EatShitPenalty + ","
        + "TaskMultiplierGreen:" + TaskMultiplierGreen + ","
        + "TaskMultiplierOrange:" + TaskMultiplierOrange + ","
        + "}";
    }

    partial void InitEnd();
}
