
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public sealed partial class SCTaskQuoteConfig : Luban.BeanBase
{
    public SCTaskQuoteConfig(ByteBuf _buf) 
    {
        SCId = _buf.ReadInt();
        Content = _buf.ReadString();
    }

    public static SCTaskQuoteConfig DeserializeSCTaskQuoteConfig(ByteBuf _buf)
    {
        return new SCTaskQuoteConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int SCId;
    /// <summary>
    /// SC弹幕内容
    /// </summary>
    public readonly string Content;
   
    public const int __ID__ = 310370729;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        InitEnd();
    }

    public override string ToString()
    {
        return "{ "
        + "SCId:" + SCId + ","
        + "Content:" + Content + ","
        + "}";
    }

    partial void InitEnd();
}
