
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Fantasy.Entitas;

public partial class Tables : Entity
{
    public InputKeyMapCategory InputKeyMapCategory {get; private set; }
    public ConstConfigCategory ConstConfigCategory {get; private set; }
    public FoodConfigCategory FoodConfigCategory {get; private set; }

    public void Init(System.Func<string, ByteBuf> loader)
    {
        InputKeyMapCategory = new InputKeyMapCategory(loader("InputKeyMapCategory"));
        ConstConfigCategory = new ConstConfigCategory(loader("ConstConfigCategory"));
        FoodConfigCategory = new FoodConfigCategory(loader("FoodConfigCategory"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        InputKeyMapCategory.ResolveRef(this);
        ConstConfigCategory.ResolveRef(this);
        FoodConfigCategory.ResolveRef(this);
    }
}
