
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Fantasy.Entitas;

public partial class Tables : Entity
{
    public InputKeyMapCategory InputKeyMapCategory {get; private set; }
    public ConstConfigCategory ConstConfigCategory {get; private set; }
    public FoodConfigCategory FoodConfigCategory {get; private set; }
    public ScoreConfigCategory ScoreConfigCategory {get; private set; }
    public SCTaskQuoteConfigCategory SCTaskQuoteConfigCategory {get; private set; }
    public DanmakuPoolConfigCategory DanmakuPoolConfigCategory {get; private set; }
    public DanmakuContentConfigCategory DanmakuContentConfigCategory {get; private set; }

    public void Init(System.Func<string, ByteBuf> loader)
    {
        InputKeyMapCategory = new InputKeyMapCategory(loader("InputKeyMapCategory"));
        ConstConfigCategory = new ConstConfigCategory(loader("ConstConfigCategory"));
        FoodConfigCategory = new FoodConfigCategory(loader("FoodConfigCategory"));
        ScoreConfigCategory = new ScoreConfigCategory(loader("ScoreConfigCategory"));
        SCTaskQuoteConfigCategory = new SCTaskQuoteConfigCategory(loader("SCTaskQuoteConfigCategory"));
        DanmakuPoolConfigCategory = new DanmakuPoolConfigCategory(loader("DanmakuPoolConfigCategory"));
        DanmakuContentConfigCategory = new DanmakuContentConfigCategory(loader("DanmakuContentConfigCategory"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        InputKeyMapCategory.ResolveRef(this);
        ConstConfigCategory.ResolveRef(this);
        FoodConfigCategory.ResolveRef(this);
        ScoreConfigCategory.ResolveRef(this);
        SCTaskQuoteConfigCategory.ResolveRef(this);
        DanmakuPoolConfigCategory.ResolveRef(this);
        DanmakuContentConfigCategory.ResolveRef(this);
    }
}
